CREATE TABLE IF NOT EXISTS books (
    id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    "year" int8 NOT NULL CHECK("year" > 0)
);
INSERT INTO public.books
(title, author, "year")
VALUES('How to read a book', 'Mortimer J. Adler', 1972);